### ISSUE TITLE
Firmware updated, but version number still v1.0.0

### ISSUE THREAD

**Issue by nickfujita** [LedgerHQ/ledger-app-ont#4]
I just reinstalled the ledger firmware for the ONT app today from the Ledger Live app, and it seems like fix for issue https://github.com/LedgerHQ/ledger-app-ont/issues/1 from commit 76356de89f4f10106a8c11727e4200b7bb9551b8 is not included. However, there is no indication to users that this update has been made. The version number of the application is still v1.0.0, so users who downloaded the app firmware before the updated will not know that the update has happened.

This is important because existing users will have to be told via support to manually uninstall and reinstall the app, even though the version number has not changed. This seems to be a poor user experience, as they have no way to know if they have the fixed version or not, without going and testing the ledger with an app that supports NEO based addresses on their ledger.

Could the version number please be incremented to v1.0.1?

**Comment by xizho10** [comment]
yes, the version 1.0.0 ,  i don't know is write in firmware or Ledger official set the version.

**Comment by nickfujita** [comment]
Then I guess the correct person to answer this question is someone from the Ledger team. Are you affiliated with the Ledger team, or know someone that is?

**Comment by xizho10** [comment]
i am from ontology.

**Comment by nickfujita** [comment]
If there is someone on the Ledger team that is watching this repo, could you please respond. We are already fielding many support questions related to the update mentioned in this issue, but since the version number of this ledger app was never updated, users think they are on the latest version of the app, but are actually not. A uninstall and reinstall on their end will solve the issue, but it's causing a lot of unnecessary confusion for users and time wasted for all.

**Comment by xizho10** [comment]
I saw the Ontology version has change to 1.2.0 in Ledger Live.

**Comment by nickfujita** [comment]
Confirmed update to v1.2.0. Closing.
